sonar.projectKey=Eagle-Eye-Solutions_avro-php
sonar.organization=eagle-eye-solutions
sonar.projectName=avro-php
sonar.sources=lib,.github
sonar.tests=test
sonar.coverage.exclusions=test/**
sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=test-report.xml
